### ISSUE TITLE
Test Issue

### ISSUE THREAD

**Issue by mariomeissner** [mobileappdevhm/CiEApp#1]
This is a test issue.

**Comment by bennyboer** [comment]
#Test 1,2,3... 
Failed... You'd better used Dimitry and Catch @hmkrivoj

**Comment by failita** [comment]
This issue was moved to failita/calc-failitame#1

**Comment by failita** [comment]
This issue was moved to failita/calc-failitame#2

**Comment by mariomeissner** [comment]
Are you having fun?

**Comment by bennyboer** [comment]
This is closed! Stop it or make another issue :D
